### ISSUE TITLE
About evaluation code

### ISSUE THREAD

**Issue by xucao-42** [KovenYu/ALP#1]
Hi, 

Recently, I was working on an illumination estimation project, and I enjoyed reading ALP a lot. 
In ALP, angular error and scale-invariant RMSE are used to evaluate the illumination estimates. However, I am unclear on how they are computed.

Is it possible to share the (pseudo-)code for computing the two metrics?
Best.

**Comment by samiragarwala** [comment]
Hi! Thank you for reaching out. We have attached our [evaluation code](https://github.com/KovenYu/ALP/files/13272756/eval_rebuttal.py.zip) which computes angular error and scale-invariant RMSE. For evaluation, we first relight spheres of different materials (mirror, shiny and diffuse) using the predicted and GT environment maps in Blender, and then run the evaluation code to generate metrics. Please feel free to reach out if you have any more questions!
